version: "3.9"

services:
  db:
    image: postgres:17
    container_name: academic-manager-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: academic_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
