POST http://localhost:3333/courses
Content-Type: application/json

{
    "title": "Curso de React Native",
    "description": "Curso de React Native bem legal",
    "price": 100
}

###

GET http://localhost:3333/courses?page=2

###

GET http://localhost:3333/courses?search=ORM&

###

GET http://localhost:3333/courses/6ab11e7b-1d20-4826-93ca-7a4f2328e987
