POST http://localhost:3333/courses
Content-Type: application/json

{
    "title": "Curso de Drizzle ORM",
    "description": "Curso de Node.js"
}

###

GET http://localhost:3333/courses

###

GET http://localhost:3333/courses/6ab11e7b-1d20-4826-93ca-7a4f2328e987